"""Accelerations"""


"""
-------------------------------------------------------------------------------

Accelerations generated by a certain entity on a given 3D position x at time t.

--------------------------------------------------------------------------------
"""


"""Acceleration generated by single potential. Static and time-dependent method."""
function acceleration(pot::P, x::AbstractVector{L}, t::T) where {P<:AbstractPotential, L<:Real, T<:Real}
    return -gradient(y->potential(pot, y, t), x)[1]
end
function acceleration(pot::P, x::AbstractVector{L}) where {P<:AbstractPotential, L<:Real}
    return -gradient(y->potential(pot, y), x)[1]
end
"""For testing potential with defined acceleration"""
function acceleration(::AutoDiffTrait, pot::P, x::AbstractVector{L}) where {P<:AbstractPotential, L<:Real}
    return -gradient(y->potential(pot, y), x)[1]
end
"""
    acceleration(pot::P, x::AbstractVector{L}, t::T) where {P<:AbstractStaticPotential, L<:Real, T<:Real}
Bridge function for static potentials
"""
function acceleration(pot::P, x::AbstractVector{L}, t::T) where {P<:AbstractStaticPotential, L<:Real, T<:Real}
    return acceleration(pot, x)
end

"""Acceleration generated by a spherical static potential"""
function acceleration(pot::P, x::AbstractVector{T}) where {P<:AbstractSphericalStaticPotential, T<:Real}
    r = sqrt( dot(x,x) )
    return -G*mass(pot, r)*x/r^3
end

"""Acceleration generated by a CompositePotential"""
function acceleration(pot::CompositePotential, x::AbstractVector{L}, t::T=0.0) where {L<:Real, T<:Real}
    sum_acc = zeros(L, 3)
    for p ∈ pot
        sum_acc .+= acceleration(p, x, t)
    end
    return sum_acc
end

"""Unitful acceleration generated by an a P <: AbstractPotential"""
function acceleration(pot::P, x::Vector{<:Unitful.Length}, t::T) where {P<:AbstractPotential, T<:Unitful.Time}
    x, t = adimensional(x, t)
    return acceleration(pot, x, t)*𝕦.a
end
function acceleration(pot::P, x::Vector{<:Unitful.Length}) where {P<:AbstractPotential}
    x = adimensional(x)
    return acceleration(pot, x)*𝕦.a
end


"""Acceleration generated by a P <: AbstractMacroParticle: reduces to its potential (single or composite)
⚠ Warning: acceleration should depend on the difference (Δx) between the position x and the position of the potential source (y). See alternative method below.
"""
function acceleration(mp::P, Δx::AbstractVector{L}, t::T=0.0) where {P<:AbstractMacroParticle, L<:Real, T<:Real}
    return acceleration(mp.pot, Δx, t)
end

"""Acceleration generated by a P <: AbstractMacroParticle: reduces to its potential (single or composite)
⚠ Warning: acceleration should depend on the difference between the position (x) and the position of the potential source (y). See alternative method above.
"""
function acceleration(mp::P, y::AbstractVector{L}, x::AbstractVector{L}, t::T=0.0) where {P<:AbstractMacroParticle, L<:Real, T<:Real}
    return acceleration(mp.pot, x-y, t)
end

"""
Acceleration generated by a P <: AbstractMacroParticleSystem
⚠ Warning: acceleration should depend on the difference (Δx) between the position x and the position of the potential sources (y).
length(y) == 3*length(mps)
"""
function acceleration(mps::P, y::AbstractVector{L}, x::AbstractVector{L}, t::T=0.0) where {P<:AbstractMacroParticleSystem, L<:Real, T<:Real}
    n = length(mps)
    acc = zero(MVector{3,L})
    for j ∈ 1:n
        Δx = SVector{3}(x[1]-y[3j-2], x[2]-y[3j-1], x[3]-y[3j])
        acc .+= acceleration(mps[j].pot, Δx, t)
    end
    return acc
end

"""
Acceleration generated by a D <: AbstractDiscreteDistribution onto an E <: AbstractEvent
⚠ Warning: acceleration should depend on the difference (Δx) between the position event.x and
the position of the potential sources (y).
length(y) == 3*length(dist)
"""
function acceleration(dist::D, y::AbstractVector{L}, event::E) where {D<:AbstractDiscreteDistribution, L<:Real, E<:AbstractEvent}
    return acceleration(dist, event.x-y, event.t)
end

"""Acceleration generated by D <: AbstractDiscreteDistribution a onto a P<:AbstractParticle
⚠ Warning: acceleration should depend on the difference (Δx) between the position p.event.x and
the position of the potential sources (y).
length(y) == 3*length(dist)
"""
function acceleration(dist::D, y::AbstractVector{L}, p::P) where {D<:AbstractDiscreteDistribution, L<:Real, P<:AbstractParticle}
    return acceleration(dist, y, p.event)
end




"""Acceleration generated by a P <: AbstractPotential when there is presence of dynamical friction
drag force.
The algorithm for the drag is dispatched according to the fric struct.
⚠ Warning: here x and v are difference vectors between the perturber and the potential source.
"""
function acceleration(fric::F, pot::P, x::AbstractVector{L}, v::AbstractVector{L}, t::T) where {P<:AbstractPotential, L<:Real, T<:Real, F<:AbstractFriction}
    return acceleration(pot, x, t) + drag(fric, pot, x, v, t)
end



"""Analytical accelerations"""

"""Allen and Santillan (generalized) halo"""

"""Hernquist potential"""
function acceleration(pot::Hernquist, x::AbstractVector{T}) where {T<:Real}
    # println("Herquist acceleration...")
    @unpack_Hernquist pot
    r = sqrt( dot(x,x) )
    return G*m / (r+a)^2 * x / r
end

"""Kepler potential"""

"""MiyamotoNagaiDisk"""
function acceleration(pot::MiyamotoNagaiDisk, x::AbstractVector{T}) where {T<:Real}
    @unpack_MiyamotoNagaiDisk pot
    y = @view x[1:2]
    bz = sqrt(b*b + x[3]*x[3])
    abz = a + bz
    fac = -G*m / (dot(y,y) + abz*abz)^(1.5)
    return fac*SVector{3,T}(x[1], x[2], x[3]*abz/bz)
end


"""NFW halo acceleration"""
function acceleration(pot::NFW, x::AbstractVector{T}) where {T<:Real}
    r = sqrt( dot(x,x) )
    return -G*pot.m*f_nfw(r/pot.a)*x/r^3
end

"""Oscillatory Kepler dependent"""

"""Plummer"""

"""PowerLawCutoff"""
function acceleration(pot::PowerLawCutoff, x::AbstractVector{L}) where {L<:Real}
    @unpack m, c, β =  pot
    r = sqrt( dot(x,x) )
    return -G * m * (gamma_inc(β, r*r/(c*c),0)[1]) * x / r^3
end

"""
------------------------------------------------------------------------------------

Accelerations received by each MacroParticle of a system at time t (mutating cache in some
of the methods below but not in specific ones, i.e. Clouds+MW, Sagittarius+Clouds+MW, etc.).

This are the accelerations needed by the ode(...).
cache acceleration is modified in-place, but not used by the ode(...).
I will have an alternative ode!(...) function that doesn't call any acceleration!(...).
------------------------------------------------------------------------------------
Two algorithms:
acceleration_c! and acceleration!

Example benchmark from testset AccelerationsMacroParticleSystem:

BenchmarkTools.Trial: 100 samples with 1 evaluation per sample.
 Range (min … max):  24.056 μs … 58.068 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     24.424 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   25.954 μs ±  5.371 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █▅
  ███▆▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▆▁▁▁▆▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄ ▄
  24.1 μs      Histogram: log(frequency) by time      51.5 μs <

 Memory estimate: 14.94 KiB, allocs estimate: 373.

BenchmarkTools.Trial: 100 samples with 1 evaluation per sample.
 Range (min … max):  37.776 μs … 91.976 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     38.600 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   39.977 μs ±  7.462 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █▅▂
  ████▆▁▁▁▁▁▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄ ▄
  37.8 μs      Histogram: log(frequency) by time      90.5 μs <

 Memory estimate: 20.86 KiB, allocs estimate: 458.

Conclusion: acceleration! is more performant than acceleration_c!
"""

selec(i::I) where {I<:Integer} = 1+3(i-1)
"""Complement function to be used in acceleration computation"""
function complement(mps::MacroParticleSystem, x::AbstractVector{L}, i::I) where {L<:Real, I<:Integer}
    n = length(mps)
    ρ = [mps[j].pot for j in 1:n if j != i]
    χ = [SVector{3,L}(
            x[selec(j)],
            x[selec(j)+1],
            x[selec(j)+2]
        ) for j in 1:n if j != i]
    return ρ, χ
end
"""Acceleration of a system of macro particles using complement"""
function acceleration_c!(mps::MacroParticleSystem, x::AbstractVector{L}, t::T=0.0) where {L<:Real, T<:Real}
    acc = mps.accelerations
    for i ∈ eachindex(mps)
        y = SVector{3,L}(x[selec(i)], x[selec(i)+1], x[selec(i)+2])
        ρ, χ = complement(mps, x, i)
        acc_sum = zero(SVector{3,L})
        for j in eachindex(ρ)
            Δx = y - χ[j]
            acc_sum += acceleration(ρ[j], Δx, t)
        end
        acc[3i-2] = acc_sum[1]
        acc[3i-1] = acc_sum[2]
        acc[3i]   = acc_sum[3]
    end
    return acc
end

"""Acceleration of a system of macro particles without using complement"""
function acceleration!(mps::MacroParticleSystem, x::AbstractVector{L}, t::T=0.0) where {L<:Real, T<:Real}
    n = length(mps)
    acc  = mps.accelerations
    @inbounds for i ∈ 1:n
        y = SVector{3,L}(x[3i-2], x[3i-1], x[3i])
        acc_sum = zero(MVector{3,L})
        for j ∈ 1:n
            i == j && continue
            χ = SVector{3,L}(x[3j-2], x[3j-1], x[3j])
            acc_sum .+= acceleration(mps[j].pot, y - χ, t)
        end
        acc[3i-2] = acc_sum[1]
        acc[3i-1] = acc_sum[2]
        acc[3i]   = acc_sum[3]
    end

    return acc
end


"""Acceleration of a system of macro particles without using complement, including dynamical friction
from all the bodies onto all the bodies.

function acceleration!(fric::Matrix{F}, mps::P, x::AbstractVector{L}, t::T=0.0) where {F<:AbstractFriction, P<:AbstractMacroParticleSystem,L<:Real, T<:Real}
"""
function acceleration!(fric::Matrix{F}, mps::MacroParticleSystem, x::AbstractVector{L}, t::T=0.0) where {F<:AbstractFriction,L<:Real, T<:Real}
    n = length(mps)
    acc  = mps.accelerations
    @inbounds for i ∈ 1:n
        i3 = 3i
        in3 = 3*(i+n)
        y = SVector{3,L}(x[i3-2], x[i3-1], x[i3])
        w = SVector{3,L}(x[in3-2], x[in3-1], x[in3])
        acc_sum = zero(MVector{3,L})
        for j ∈ 1:n
            i == j && continue
            j3 = 3j
            jn3 = 3*(j+n)
            χ = SVector{3,L}(x[j3-2], x[j3-1], x[j3])
            Ω = SVector{3,L}(x[jn3-2], x[jn3-1], x[jn3])
            acc_sum .+= acceleration(fric[i,j], mps[j].pot, y - χ, w - Ω, t)
        end
        acc[3i-2] = acc_sum[1]
        acc[3i-1] = acc_sum[2]
        acc[3i]   = acc_sum[3]
    end

    return acc
end



"""Acceleration for LargeCloudMW system without friction"""
function acceleration(system::LargeCloudMW, u::AbstractVector{L}, t::T=0.0) where {L<:Real, T<:Real}
    @unpack mw, cloud = system
    Δx = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    acc_at_cloud = acceleration(mw.pot, Δx, t)
    acc_at_mw = acceleration(cloud.pot, -Δx, t)
    return SVector{6,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_cloud[1], acc_at_cloud[2], acc_at_cloud[3])
end


"""Acceleration for LargeCloudMW system with dynamical friction"""
function acceleration(fric::F, system::LargeCloudMW, u::AbstractVector{L}, t::T=0.0) where { F<:AbstractFriction, L<:Real, T<:Real}
    @unpack mw, cloud = system
    Δx = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    Δv = SVector{3,L}(u[10]-u[7], u[11]-u[8], u[12]-u[9])
    acc_at_cloud = acceleration(fric, mw.pot, Δx, Δv, t)
    acc_at_mw = acceleration(cloud.pot, -Δx, t)
    return SVector{6,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_cloud[1], acc_at_cloud[2], acc_at_cloud[3])
end


"""Acceleration for CloudsMW system without frictions. Including the reflex acceleration of both clouds on the MW."""
function acceleration(system::CloudsMW, u::AbstractVector{L}, t::T=0.0) where {L<:Real, T<:Real}
    @unpack mw, large, small = system
    Δx_mw_lc = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    Δx_mw_sc = SVector{3,L}(u[7]-u[1], u[8]-u[2], u[9]-u[3])
    Δx_lc_sc = SVector{3,L}(u[7]-u[4], u[8]-u[5], u[9]-u[6])
    acc_at_mw = acceleration(large.pot, -Δx_mw_lc, t) +
                acceleration(small.pot, -Δx_mw_sc, t)
    acc_at_lc = acceleration(mw.pot, Δx_mw_lc, t) +
                acceleration(small.pot, -Δx_lc_sc, t)
    acc_at_sc= acceleration(mw.pot, Δx_mw_sc, t) +
                acceleration(large.pot, Δx_lc_sc, t)
    return SVector{9,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_lc[1], acc_at_lc[2], acc_at_lc[3],
             acc_at_sc[1], acc_at_sc[2], acc_at_sc[3])
end

"""Acceleration for CloudsMW system with MW's dynamical friction on both clouds and the dynamical friction of the large cloud on the small cloud. And the reflex acceleration of both clouds on the MW."""
function acceleration(fric::Tuple{F,F,F}, system::CloudsMW, u::AbstractVector{L}, t::T=0.0) where { F<:AbstractFriction, L<:Real, T<:Real}
    @unpack mw, large, small = system
    Δx_mw_lc = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    Δv_mw_lc = SVector{3,L}(u[13]-u[10], u[14]-u[11], u[15]-u[12])
    Δx_mw_sc = SVector{3,L}(u[7]-u[1], u[8]-u[2], u[9]-u[3])
    Δv_mw_sc = SVector{3,L}(u[16]-u[10], u[17]-u[11], u[18]-u[12])
    Δx_lc_sc = SVector{3,L}(u[7]-u[4], u[8]-u[5], u[9]-u[6])
    Δv_lc_sc = SVector{3,L}(u[16]-u[13], u[17]-u[14], u[18]-u[15])
    acc_at_mw = acceleration(large.pot, -Δx_mw_lc, t) +
                acceleration(small.pot, -Δx_mw_sc, t)
    acc_at_lc = acceleration(fric[1], mw.pot, Δx_mw_lc, Δv_mw_lc, t) +
                acceleration(small.pot, -Δx_lc_sc, t)
    acc_at_sc= acceleration(fric[2], mw.pot, Δx_mw_sc, Δv_mw_sc, t) +
                acceleration(fric[3], large.pot, Δx_lc_sc, Δv_lc_sc, t)
    return SVector{9,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_lc[1], acc_at_lc[2], acc_at_lc[3],
             acc_at_sc[1], acc_at_sc[2], acc_at_sc[3])
end

"""Acceleration for CloudsMW system similar to above method plus the incorporation of the drift suffered by the MW due to the Large cloud."""
function acceleration(fric::Tuple{F,F,F,F}, system::CloudsMW, u::AbstractVector{L}, t::T=0.0) where { F<:AbstractFriction, L<:Real, T<:Real}
    @unpack mw, large, small = system
    Δx_mw_lc = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    Δv_mw_lc = SVector{3,L}(u[13]-u[10], u[14]-u[11], u[15]-u[12])
    Δx_mw_sc = SVector{3,L}(u[7]-u[1], u[8]-u[2], u[9]-u[3])
    Δv_mw_sc = SVector{3,L}(u[16]-u[10], u[17]-u[11], u[18]-u[12])
    Δx_lc_sc = SVector{3,L}(u[7]-u[4], u[8]-u[5], u[9]-u[6])
    Δv_lc_sc = SVector{3,L}(u[16]-u[13], u[17]-u[14], u[18]-u[15])
    acc_at_mw = acceleration(fric[4], large.pot, -Δx_mw_lc, -Δv_mw_lc, t) +
                acceleration(small.pot, -Δx_mw_sc, t)
    acc_at_lc = acceleration(fric[1], mw.pot, Δx_mw_lc, Δv_mw_lc, t) +
                acceleration(small.pot, -Δx_lc_sc, t)
    acc_at_sc= acceleration(fric[2], mw.pot, Δx_mw_sc, Δv_mw_sc, t) +
                acceleration(fric[3], large.pot, Δx_lc_sc, Δv_lc_sc, t)
    return SVector{9,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_lc[1], acc_at_lc[2], acc_at_lc[3],
             acc_at_sc[1], acc_at_sc[2], acc_at_sc[3])
end

"""Acceleration for SatelliteCloudMW system with dynamical friction for the cloud only. And the reflex acceleration of only the cloud on the MW."""
function acceleration(fric::F, system::SatelliteCloudMW, u::AbstractVector{L}, t::T=0.0) where { F<:AbstractFriction, L<:Real, T<:Real}
    @unpack mw, cloud, satellite = system
    Δx = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    Δv = SVector{3,L}(u[13]-u[10], u[14]-u[11], u[15]-u[12])
    δx = SVector{3,L}(u[7]-u[1], u[8]-u[2], u[9]-u[3])
    δx₂ = SVector{3,L}(u[7]-u[4], u[8]-u[5], u[9]-u[6])
    acc_at_mw = acceleration(cloud.pot, -Δx)
    acc_at_cloud = acceleration(fric, mw.pot, Δx, Δv, t)
    acc_at_sat = acceleration(mw.pot, δx) + acceleration(cloud.pot,δx₂)
    return SVector{9,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_cloud[1], acc_at_cloud[2], acc_at_cloud[3],
             acc_at_sat[1], acc_at_sat[2], acc_at_sat[3])
end

"""Acceleration for SatelliteCloudMW system with MW's dynamical friction for the cloud and the satellite. And the reflex acceleration of only the cloud on the MW."""
function acceleration(fric::Tuple{F,F}, system::SatelliteCloudMW, u::AbstractVector{L}, t::T=0.0) where { F<:AbstractFriction, L<:Real, T<:Real}
    @unpack mw, cloud, satellite = system
    Δx = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    Δv = SVector{3,L}(u[13]-u[10], u[14]-u[11], u[15]-u[12])
    δx = SVector{3,L}(u[7]-u[1], u[8]-u[2], u[9]-u[3])
    δv = SVector{3,L}(u[16]-u[10], u[17]-u[11], u[18]-u[12])
    δx₂ = SVector{3,L}(u[7]-u[4], u[8]-u[5], u[9]-u[6])
    acc_at_mw = acceleration(cloud.pot, -Δx)
    acc_at_cloud = acceleration(fric[1], mw.pot, Δx, Δv, t)
    acc_at_sat = acceleration(fric[2], mw.pot, δx, δv, t) + acceleration(cloud.pot,δx₂)
    return SVector{9,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_cloud[1], acc_at_cloud[2], acc_at_cloud[3],
             acc_at_sat[1], acc_at_sat[2], acc_at_sat[3])
end



" 🚧 Below is work in progress! 🛠️"

"""
Acceleration for CloudsMW system with mutual dynamical friction. This should be equal to the result
of using evolve with ::MutualFrictionTrait, that implies using the method acceleration!(fric::Matrix{F}, mps::P, x::AbstractVector{L}, t::T=0.0) where {F<:AbstractFriction, P<:AbstractMacroParticleSystem,L<:Real, T<:Real}, for the corresponding MacroParticleSystem.
⚠...not tested yet... 🧰
Corresponding ode() and evolution() functions not written yet. Maybe never will be completed, as this system
can be solved using MacroParticleSystem approach.

I prefer to use the method above:
    acceleration(fric::Tuple{F,F}, system::CloudsMW, ...
where only MW friction effect is considered on both clouds.
"""
function acceleration(fric::Matrix{F}, system::CloudsMW, u::AbstractVector{L}, t::T=0.0) where { F<:AbstractFriction, L<:Real, T<:Real}
    @unpack mw, large, small = system
    Δx_mw_lc = SVector{3,L}(u[4]-u[1], u[5]-u[2], u[6]-u[3])
    Δv_mw_lc = SVector{3,L}(u[13]-u[10], u[14]-u[11], u[15]-u[12])
    Δx_mw_sc = SVector{3,L}(u[7]-u[1], u[8]-u[2], u[9]-u[3])
    Δv_mw_sc = SVector{3,L}(u[16]-u[10], u[17]-u[11], u[18]-u[12])
    Δx_lc_sc = SVector{3,L}(u[7]-u[4], u[8]-u[5], u[9]-u[6])
    Δv_lc_sc = SVector{3,L}(u[16]-u[13], u[17]-u[14], u[18]-u[15])
    acc_at_mw = acceleration(fric[1,2], large.pot, -Δx_mw_lc, -Δv_mw_lc, t) +
                acceleration(fric[1,3], small.pot, -Δx_mw_sc, -Δv_mw_sc, t)
    acc_at_lc = acceleration(fric[2,1], mw.pot, Δx_mw_lc, Δv_mw_lc, t) +
                   acceleration(fric[2,3], small.pot, -Δx_lc_sc, -Δv_lc_sc, t)
    acc_at_sc= acceleration(fric[3,1], mw.pot, Δx_mw_sc, Δv_mw_sc, t) +
                 acceleration(fric[3,2], large.pot, Δx_lc_sc, Δv_lc_sc, t)
    return SVector{9,L}(acc_at_mw[1], acc_at_mw[2], acc_at_mw[3],
             acc_at_lc[1], acc_at_lc[2], acc_at_lc[3],
             acc_at_sc[1], acc_at_sc[2], acc_at_sc[3])
end