"""Densities"""

"""

General method for spherical static potentials
"""
function density(pot::P, x::AbstractVector{L}) where {P<:AbstractStaticPotential, L<:Real}
    Φ(x) = potential(pot,x)
    return sum(first(diaghessian(Φ, x))) / (4π*G)
end

"""
    density(pot::P, x::AbstractVector{L}, t::T) where {P<:AbstractStaticPotential, L<:Real, T<:Real}
Bridge function for static potentials
"""
function density(pot::P, x::AbstractVector{L}, t::T) where {P<:AbstractStaticPotential, L<:Real, T<:Real}
    return density(pot, x)
end

"""
    density(pot::P, x::AbstractVector{L}) where {P<:AbstractStaticPotential, L<:Real}
Bridge function for spherical static potentials
"""
function density(pot::P, x::AbstractVector{L}) where {P<:AbstractSphericalStaticPotential, L<:Real}
    r = sqrt( dot(x,x) )
    return density(pot, r)
end

"""
    density(pot::P, r::L) where {P<:AbstractSphericalStaticPotential, L<:Real}
General method for spherical static potentials
"""
function density(pot::P, r::L) where {P<:AbstractSphericalStaticPotential, L<:Real}
    return 1 / (4π*r^2) * gradient(y->mass(pot, y), r)[1]
end

"""
    density(::DistributionTrait, pot::P, r::L) where {P<:AbstractSphericalStaticPotential, L<:Real}
Trait method for spherical static potentials, computed integrating in velocity space the
phase-space distribution function.
For the moment only available for the isotropic case.
"""
function density(::DistributionTrait, pot::P, r::L) where {P<:AbstractSphericalStaticPotential, L<:Real}
    println("👀 Important to define the distribution function method for the spherical and static case:
    distribution(pot, r, v).")
    f(s,p) = s^2 * distribution(pot, p, s)
    prob = IntegralProblem(f, (0, Inf), r)
    return  4π * solve(prob, QuadGKJL()).u
end



"""Density of a AbstractCompositePotential"""
function density(pot::C, x::AbstractVector{L}, t::T=0.0) where {C<:AbstractCompositePotential, L<:Real, T<:Real}
    ρ = zero(L)
    for p ∈ pot
        ρ += density(p, x, t)
    end
    return ρ
end

"""Unitful acceleration generated by an a P <: AbstractPotential"""
function density(pot::P, x::Vector{<:Unitful.Length}, t::T) where {P<:AbstractPotential, T<:Unitful.Time}
    x, t = adimensional(x, t)
    return density(pot, x, t)*𝕦.ρ
end
function density(pot::P, x::Vector{<:Unitful.Length}) where {P<:AbstractPotential}
    x = adimensional(x)
    return density(pot, x)*𝕦.ρ
end


"""Concrete potentials"""

"""Spherical"""

"""Allen and Santillan (generalized by Irrgang 2013) halo"""
function density(pot::AllenSantillanHalo, r::L) where {L<:Real}
    @unpack_AllenSantillanHalo pot
    p(y) = (y/a)^(γ-1)
    f(y) = 1 + p(y)
    h(y) = γ + p(y)
    if r < Λ
        return m / (4π*a*r^2) * p(r) * h(r) / f(r)^2
    else
        return 0.0
    end
end


"""Hernquist potential"""
function density(pot::Hernquist, r::L) where {L<:Real}
    @unpack_Hernquist pot
    r_a = r / a
    return m/(2π*a^3) / ( r_a * (1+r_a)^3 )
end

"""Kepler potential"""
function density(pot::Kepler, r::L) where {L<:Real}
    @unpack m = pot
    if r < 𝕡.ϵ_r
        return Inf
    else
        return 0.0
    end
end

"""
    NFW
    Galactic Dynamics 2nd edition, Binney and Treamaine (2008)
"""
function density(pot::NFW, r::L) where {L<:Real}
    @unpack a, ρ₀ = pot
    r_a = r / a
    return ρ₀/r_a/(1+r_a)^2
end


"""
    Plummer density

     /*  pars:
            - G (Gravitational constant)
            - m (mass scale)
            - b (length scale)
    */
    double r2 = q[0]*q[0] + q[1]*q[1] + q[2]*q[2];
    return 3*pars[1] / (4*M_PI*pars[2]*pars[2]*pars[2]) * pow(1 + r2/(pars[2]*pars[2]), -2.5);
    Expression from Gala
"""
function density(pot::Plummer, r::L) where {L<:Real}
    @unpack_Plummer pot
    return 3m/(4π*a^3) / (1+r^2/(a*a))^(2.5)
end


"""
    PowerLawCutoff density

    density(pot::PowerLawCutoff, r::AbstractVector{L}) where {L<:Real}
    Expression from Gala.
"""
function density(pot::PowerLawCutoff, r::L) where {L<:Real}
    @unpack α, c, 𝔸 =  pot
    return 𝔸 / r^α * exp(-r*r/(c*c))
end


"""Axisymmetric"""

"""
    Miyamoto-Nagai disk density
    Bovy book: eq. 7.16.
"""
function density(pot::MiyamotoNagai, x::AbstractVector{L}) where {L<:Real}
    @unpack_MiyamotoNagai pot
    y = @view x[1:2]
    R² = dot(y,y)
    b² = b*b
    bz² = b² + x[3]*x[3]
    bz = sqrt(bz²)
    abz = a + bz
    return (m*b²/4π)*(a*R²+(3*bz+a)*abz^2)/((R²+abz*abz)^2.5*(bz²)^1.5)
end
