"""Enclosed mass"""

"""Unitful enclosed mass for a P <: AbstractPotential"""
function mass(pot::P, x::Vector{<:Unitful.Length}, t::T) where {P<:AbstractPotential, T<:Unitful.Time}
    x, t = adimensional(x, t)
    return mass(pot, x, t)*𝕦.m
end
function mass(pot::P, x::Vector{<:Unitful.Length}) where {P<:AbstractStaticPotential}
    x = adimensional(x)
    return mass(pot, x)*𝕦.m
end
function mass(pot::P, r::L) where {P<:AbstractSphericalStaticPotential, L<:Unitful.Length}
    r = adimensional(r)
    return mass(pot, r)*𝕦.m
end

"""Unitful enclosed mass for a P <: AbstractPotential using an F<:FromTrait"""
function mass(trait::F, pot::P, x::Vector{<:Unitful.Length}, t::T) where {F<:FromTrait, P<:AbstractPotential, T<:Unitful.Time}
    x, t = adimensional(x, t)
    return mass(trait, pot, x, t)*𝕦.p
end
function mass(trait::F, pot::P, x::Vector{<:Unitful.Length}) where {F<:FromTrait, P<:AbstractPotential}
    x = adimensional(x)
    return mass(trait, pot, x)*𝕦.p
end
"""Unitful potential generated by an a P <: AbstractSphericalStaticPotential"""
function mass(trait::F, pot::P, r::L) where {F<:FromTrait, P<:AbstractSphericalStaticPotential, L<:Unitful.Length}
    r = adimensional(r)
    return mass(trait, pot, r)*𝕦.p
end

"""
potential(pot::P, x::AbstractVector{L}, t::T) where {P<:AbstractStaticPotential, L<:Real, T<:Real}
Bridge function for static potentials
"""
function mass(pot::P, x::AbstractVector{L}, t::T) where {P<:AbstractStaticPotential, L<:Real, T<:Real}
    return mass(pot, x)
end
function mass(trait::F, pot::P, x::AbstractVector{L}, t::T) where {F<:FromTrait, P<:AbstractSphericalStaticPotential, L<:Real, T<:Real}
    return mass(trait, pot, x)
end

"""
Bridge function for spherical static potentials.
Enclosed mass for P <:AbstractSphericalStaticPotential at position x"""
function mass(pot::P, x::AbstractVector{L}) where {P<:AbstractSphericalStaticPotential, L<:Real}
    r = sqrt( dot(x,x) )
    return mass(pot, r)
end
function mass(trait::F, pot::P, x::AbstractVector{L}) where {F<:FromTrait, P<:AbstractSphericalStaticPotential, L<:Real}
    r  = sqrt(  dot(x,x)  )
    return mass(trait, pot, r)
end

""" Enclosed mass corresponding to a single spherical and static potential (default).
    M(r) = (r^2/G)*dΦ(r)/dr = -a(r)*r^2/G
    If acceleration is not defined, then by default it uses AD with the potential
    function.
"""
function mass(pot::P, r::L) where {P<:AbstractSphericalStaticPotential, L<:Real}
    return -r^2 / G * acceleration(pot,r)
end

""" FromDensityTrait 🦆 -> Dual use
    Enclosed mass corresponding to a single spherical and static potential.
    M(r) = 4π ∫₀ʳ s^2 * ρ(s) ds

    Apply in case:

    1) an analytical formula for m(r), a(r) or Φ(r) is given but we need to test. Examples:
    @test mass(FromDensityTrait(), pot, r) ≈ mass(pot, r)

    2) Neither m(r) nor a(r) nor Φ(r) are available. Example:
    mass(pot::SomePotential, x::L) where {L<:Real} = mass(FromDensityTrait(), pot, x)
"""
function mass(::FromDensityTrait, pot::P, r::L) where {P<:AbstractSphericalStaticPotential, L<:Real}
    f(s,p) = s^2 * density(pot, s)
    prob = IntegralProblem(f, (0, r))
    sol = solve(prob, QuadGKJL(); abstol=𝕚.abstol, reltol=𝕚.reltol)
    if sol.resid > max(𝕚.abstol, 𝕚.reltol * norm(sol.u))
        @warn "Tolerance not reached within maxevals" sol.u sol.resid
    end
    return  4π*sol.u
end



"""Specific potentials"""


"""Allen and Santillan (generalized by Irrgang 2013) halo"""
function mass(pot::AllenSantillanHalo, r::L) where {L<:Real}
    @unpack_AllenSantillanHalo pot
    f(y) = 1 + (y/a)^(γ-1)
    g(y) = m * (y/a)^γ / f(y)
    if r < Λ
        return g(r)
    else
        return g(Λ)
    end
end

"""Hernquist"""
mass(pot::Hernquist, r::L) where {L<:Real} = pot.m*(r/pot.a)^2/(1+r/pot.a)^2

"""Kepler"""
mass(pot::Kepler, r::L=0.0) where {L<:Real} = pot.m

"""NFW mass"""
mass(pot::NFW, r::L) where {L<:Real} = pot.m*f_nfw(r/pot.a)


"""Plummer Sphere"""
mass(pot::Plummer, r::L) where {L<:Real}  = pot.m / (1 + (pot.a/r)^2 )^1.5

"""PowerLawCutoff mass(r)"""
function _mass(pot::PowerLawCutoff, r::L) where {L<:Real}
    @unpack α, c, β, Γ_β, 𝔸 =  pot
    return 2π*𝔸*c^(3-α)*Γ_β*gamma_inc(β, r*r/(c*c),0)[1]
end
mass(pot::PowerLawCutoff, r::L) where {L<:Real} = pot.m*gamma_inc(pot.β, (r/pot.c)^2, 0)[1]

