"""Masses"""

"""Unitful acceleration generated by an a P <: AbstractPotential"""
function mass(pot::P, x::Vector{<:Unitful.Length}, t::T) where {P<:AbstractPotential, T<:Unitful.Time}
    x, t = adimensional(x, t)
    return mass(pot, x, t)*𝕦.m
end
function mass(pot::P, x::Vector{<:Unitful.Length}) where {P<:AbstractPotential}
    x = adimensional(x)
    return mass(pot, x)*𝕦.m
end

""" Enclosed mass for P <:AbstractSphericalStaticPotential at position x"""
function mass(pot::P, x::AbstractVector{L}) where {P<:AbstractSphericalStaticPotential, L<:Real}
    r = sqrt( dot(x,x) )
    return mass(pot, r)
end


"""NFW mass"""
mass(pot::NFW, r::L) where {L<:Real} = pot.m*f_nfw(r/pot.a)


"""
    Plummer Sphere
"""
mass(pot::Plummer, r::L) where {L<:Real}  = pot.m / (1 + (pot.a/r)^2 )^1.5

"""
    PowerLawCutoff mass(r)

"""
function _mass(pot::PowerLawCutoff, r::L) where {L<:Real}
    @unpack α, c, β, Γ_β, 𝔸 =  pot
    return 2π*𝔸*c^(3-α)*Γ_β*gamma_inc(β, r*r/(c*c),0)[1]
end
mass(pot::PowerLawCutoff, r::L) where {L<:Real} = pot.m*gamma_inc(pot.β, (r/pot.c)^2, 0)[1]